feat: git commit refactor (#1529)
Co-authored-by: KamalArya <kamal749@gmail.com>
Co-authored-by: popoveugene <42543333+popoveugene@users.noreply.github.com>
Co-authored-by: KamalArya <42619309+KamalArya@users.noreply.github.com>
Co-authored-by: qubership-actions[bot] <qubership-actions[bot]@users.noreply.github.com>

diff --git a/github_workflows/instance-repo-pipeline/.github/workflows/Envgene.yml b/github_workflows/instance-repo-pipeline/.github/workflows/Envgene.yml
--- a/github_workflows/instance-repo-pipeline/.github/workflows/Envgene.yml
+++ b/github_workflows/instance-repo-pipeline/.github/workflows/Envgene.yml
@@ -102,6 +102,7 @@ jobs:
       - name: Repository Checkout
         uses: actions/checkout@v4.1.0
         with:
+          fetch-depth: 1
           persist-credentials: false
 
       - name: Load environment variables from configuration files
@@ -163,7 +164,7 @@ jobs:
       - name: Repository Checkout
         uses: actions/checkout@v4.1.0
         with:
-          fetch-depth: 0
+          fetch-depth: 1
 
       ### ENV VARS PROCESSING - START ###
       - name: Download environment-file
@@ -457,8 +458,8 @@ jobs:
               /module/scripts/utils/handle_certs.sh
               # Execute git commit with proper error handling
               echo 'Executing git commit operations...'
-              if ! /module/scripts/git_commit.sh; then
-                echo 'git_commit.sh failed with exit code '\$?
+              if ! python /module/scripts/git_commit.py; then
+                echo 'git_commit.py failed with exit code '\$?
                 exit 1
               fi
 
